apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: quay.io/buildah/stable:latest
      workingDir: $(workspaces.source.path)
      script: |
        # Use VFS to bypass kernel permission issues
        # and isolation=chroot to avoid user namespace mapping errors
        buildah --storage-driver=vfs bud \
          --isolation=chroot \
          -t $(params.IMAGE) .

        # Push the image to the internal OpenShift registry
        buildah --storage-driver=vfs push \
          --tls-verify=false \
          --digestfile ./image-digest \
          $(params.IMAGE) \
          docker://$(params.IMAGE)
      securityContext:
        privileged: false
        runAsUser: 1000
