apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: quay.io/buildah/stable:latest
      workingDir: $(workspaces.source.path)
      script: |
        # Use vfs and ignore-chown-errors to bypass restricted UID mapping
        buildah --storage-driver=vfs bud \
          --isolation=chroot \
          --ignore-chown-errors \
          -t $(params.IMAGE) .
      securityContext:
        privileged: false
