apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: source
  steps:
    - name: build
      image: quay.io/buildah/stable:latest
      workingDir: $(workspaces.source.path)
      # Use --storage-driver=vfs to avoid needing privileged host mounts
      script: |
        export BUILDAH_ISOLATION=chroot
        buildah --storage-driver=vfs bud -t $(params.IMAGE) .
      securityContext:
        privileged: false
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        capabilities:
          add: ["SETFCAP"]
