apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: quay.io/buildah/stable:latest
      workingDir: $(workspaces.source.path)
      # We add BUILDAH_FORMAT and force the VFS driver via environment
      env:
        - name: STORAGE_DRIVER
          value: vfs
      script: |
        # Use --unshare-user to bypass the GID/UID mapping requirement
        buildah bud \
          --storage-driver=vfs \
          --isolation=chroot \
          --layers \
          -t $(params.IMAGE) .

        buildah push \
          --storage-driver=vfs \
          --tls-verify=false \
          $(params.IMAGE) \
          docker://$(params.IMAGE)
      securityContext:
        privileged: false
        capabilities:
          add: ["SETFCAP"]
