apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: quay.io/buildah/stable:latest
      workingDir: $(workspaces.source.path)
      script: |
        # Use VFS driver and force chroot isolation for restricted environments
        # If --ignore-chown-errors is not supported, we use standard build
        buildah --storage-driver=vfs bud \
          --isolation=chroot \
          -t $(params.IMAGE) .
          
        # Note: We are only building locally here. 
        # In a real pipeline, you would also 'buildah push' to the registry.
      securityContext:
        privileged: false
        runAsUser: 1000
