apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
spec:
  workspaces:
    - name: source
  params:
    - name: image
      type: string
      default: "python:3.9-slim"
    - name: args
      type: string        # Changed from array to string
      default: "."        # Changed default to a simple string
  steps:
    - name: flake8
      image: $(params.image)
      workingDir: $(workspaces.source.path)
      script: |
        set -e
        export PATH=$PATH:/home/step-user/.local/bin
        python -m pip install --upgrade pip
        python -m pip install flake8
        flake8 $(params.args)
